import uuid

from app.services.clarification_service import (
    analyze_question
)

from app.services.conversation_service import (
    create_conversation,
    get_conversation,
    update_conversation
)

from app.services.sql_generator import (
    generate_sql
)

from app.services.sql_validator import (
    validate_sql
)

from app.services.sql_executor import (
    execute_readonly_sql
)

from app.services.answer_service import (
    generate_answer
)


# ============================================================
# PROCESS NEW QUERY
# ============================================================

async def process_query(
    question: str
):
    """
    Main QueryMind query pipeline.

    Flow:

    User question
          ↓
    Intent Classification
          ↓
    ┌──────────────┬───────────────┬──────────────┐
    │              │               │
    CLEAR      AMBIGUOUS      UNSUPPORTED
    │              │               │
    ↓              ↓               ↓
    SQL         Clarify          Reject
    │
    ↓
    Schema RAG
    │
    ↓
    Groq
    │
    ↓
    SQL Validation
    │
    ↓
    Read-only PostgreSQL
    │
    ↓
    Natural-language answer
    """

    # ========================================================
    # 1. Analyze user intent
    # ========================================================

    intent = await analyze_question(
        question
    )

    intent_type = intent.get(
        "intent",
        "AMBIGUOUS"
    )

    # ========================================================
    # 2. UNSUPPORTED
    # ========================================================

    if intent_type == "UNSUPPORTED":

        return {
            "status": "unsupported",
            "question": question,
            "reason": intent.get(
                "reason",
                "The requested information "
                "is not available in the database."
            )
        }

    # ========================================================
    # 3. AMBIGUOUS
    # ========================================================

    if intent_type == "AMBIGUOUS":

        conversation_id = str(
            uuid.uuid4()
        )

        create_conversation(
            conversation_id=conversation_id,
            question=question
        )

        update_conversation(
            conversation_id,
            clarification=intent,
            status="awaiting_clarification"
        )

        return {
            "status": "clarification_required",
            "conversation_id": conversation_id,
            "question": intent.get(
                "question"
            ),
            "options": intent.get(
                "options",
                []
            ),
            "reason": intent.get(
                "reason"
            )
        }

    # ========================================================
    # 4. CLEAR
    # ========================================================

    if intent_type != "CLEAR":

        return {
            "status": "error",
            "question": question,
            "reason": (
                "Unable to determine the "
                "intent of the question."
            )
        }

    # ========================================================
    # 5. Generate SQL
    # ========================================================

    try:

        sql_result = await generate_sql(
            question=question
        )

    except Exception as exc:

        return {
            "status": "sql_generation_failed",
            "question": question,
            "error": str(exc)
        }

    # --------------------------------------------------------
    # Make sure SQL generation returned the expected structure
    # --------------------------------------------------------

    if not isinstance(
        sql_result,
        dict
    ):

        return {
            "status": "sql_generation_failed",
            "question": question,
            "error": (
                "SQL generator returned "
                "an invalid response."
            )
        }

    sql = sql_result.get(
        "sql"
    )

    if not sql:

        return {
            "status": "sql_generation_failed",
            "question": question,
            "error": (
                "SQL generator did not "
                "return SQL."
            )
        }

    # ========================================================
    # 6. Handle unsupported SQL generated by the model
    # ========================================================

    if sql.strip().upper() == "UNSUPPORTED":

        return {
            "status": "unsupported",
            "question": question,
            "reason": (
                "The database schema does not "
                "contain enough information to "
                "answer this question."
            )
        }

    # ========================================================
    # 7. Validate generated SQL
    # ========================================================

    try:

        validation = await validate_sql(
            sql
        )

    except Exception as exc:

        return {
            "status": "sql_validation_failed",
            "question": question,
            "sql": sql,
            "error": str(exc)
        }

    # ========================================================
    # 8. Reject invalid SQL
    # ========================================================

    if not validation.get(
        "valid",
        False
    ):

        return {
            "status": "sql_rejected",
            "question": question,
            "reason": validation.get(
                "reason",
                "SQL validation failed."
            ),
            "sql": sql,
            "validation": validation
        }

    # ========================================================
    # 9. Execute validated SQL
    # ========================================================

    try:

        execution = await execute_readonly_sql(
            sql
        )

    except Exception as exc:

        return {
            "status": "execution_failed",
            "question": question,
            "sql": sql,
            "validation": validation,
            "error": str(exc)
        }

    # ========================================================
    # 10. Handle execution failure
    # ========================================================

    if not execution.get(
        "success",
        False
    ):

        return {
            "status": "execution_failed",
            "question": question,
            "sql": sql,
            "validation": validation,
            "error": execution.get(
                "error",
                "Database execution failed."
            )
        }

    # ========================================================
    # 11. Generate natural-language answer
    # ========================================================

    try:

        answer = await generate_answer(
            question=question,
            sql=sql,
            rows=execution.get(
                "rows",
                []
            )
        )

    except Exception as exc:

        return {
            "status": "answer_generation_failed",
            "question": question,
            "sql": sql,
            "validation": validation,
            "row_count": execution.get(
                "row_count",
                0
            ),
            "rows": execution.get(
                "rows",
                []
            ),
            "error": str(exc)
        }

    # ========================================================
    # 12. Return final result
    # ========================================================

    return {
        "status": "query_executed",
        "question": question,
        "sql": sql,
        "validation": validation,
        "row_count": execution.get(
            "row_count",
            0
        ),
        "rows": execution.get(
            "rows",
            []
        ),
        "answer": answer,
        "retrieved_schema": sql_result.get(
            "retrieved_schema",
            []
        )
    }


# ============================================================
# PROCESS CLARIFICATION
# ============================================================

async def process_clarification(
    conversation_id: str,
    answer: str
):
    """
    Continue a query after the user answers
    a clarification question.
    """

    # ========================================================
    # 1. Retrieve conversation
    # ========================================================

    conversation = get_conversation(
        conversation_id
    )

    if conversation is None:

        return {
            "status": "error",
            "reason": "Conversation not found."
        }

    # ========================================================
    # 2. Check conversation state
    # ========================================================

    if conversation.get(
        "status"
    ) != "awaiting_clarification":

        return {
            "status": "error",
            "reason": (
                "Conversation is not awaiting "
                "clarification."
            )
        }

    # ========================================================
    # 3. Get original question
    # ========================================================

    original_question = conversation.get(
        "original_question"
    )

    if not original_question:

        return {
            "status": "error",
            "reason": (
                "Original question was not "
                "found in the conversation."
            )
        }

    # ========================================================
    # 4. Combine original question + clarification
    # ========================================================

    clarified_question = (
        f"{original_question}\n\n"
        f"User clarification: {answer}"
    )

    # ========================================================
    # 5. Generate SQL
    # ========================================================

    try:

        sql_result = await generate_sql(
            question=clarified_question
        )

    except Exception as exc:

        update_conversation(
            conversation_id,
            clarification=answer,
            status="sql_generation_failed"
        )

        return {
            "status": "sql_generation_failed",
            "conversation_id": conversation_id,
            "error": str(exc)
        }

    if not isinstance(
        sql_result,
        dict
    ):

        update_conversation(
            conversation_id,
            clarification=answer,
            status="sql_generation_failed"
        )

        return {
            "status": "sql_generation_failed",
            "conversation_id": conversation_id,
            "error": (
                "SQL generator returned "
                "an invalid response."
            )
        }

    sql = sql_result.get(
        "sql"
    )

    if not sql:

        update_conversation(
            conversation_id,
            clarification=answer,
            status="sql_generation_failed"
        )

        return {
            "status": "sql_generation_failed",
            "conversation_id": conversation_id,
            "error": (
                "SQL generator did not "
                "return SQL."
            )
        }

    # ========================================================
    # 6. Handle unsupported SQL
    # ========================================================

    if sql.strip().upper() == "UNSUPPORTED":

        update_conversation(
            conversation_id,
            clarification=answer,
            status="unsupported",
            generated_sql=sql
        )

        return {
            "status": "unsupported",
            "conversation_id": conversation_id,
            "reason": (
                "The database schema does not "
                "contain enough information to "
                "answer this question."
            )
        }

    # ========================================================
    # 7. Validate generated SQL
    # ========================================================

    try:

        validation = await validate_sql(
            sql
        )

    except Exception as exc:

        update_conversation(
            conversation_id,
            clarification=answer,
            status="sql_validation_failed",
            generated_sql=sql
        )

        return {
            "status": "sql_validation_failed",
            "conversation_id": conversation_id,
            "sql": sql,
            "error": str(exc)
        }

    # ========================================================
    # 8. Reject invalid SQL
    # ========================================================

    if not validation.get(
        "valid",
        False
    ):

        update_conversation(
            conversation_id,
            clarification=answer,
            status="sql_rejected",
            generated_sql=sql
        )

        return {
            "status": "sql_rejected",
            "conversation_id": conversation_id,
            "reason": validation.get(
                "reason",
                "SQL validation failed."
            ),
            "sql": sql,
            "validation": validation
        }

    # ========================================================
    # 9. Execute validated SQL
    # ========================================================

    try:

        execution = await execute_readonly_sql(
            sql
        )

    except Exception as exc:

        update_conversation(
            conversation_id,
            clarification=answer,
            status="execution_failed",
            generated_sql=sql
        )

        return {
            "status": "execution_failed",
            "conversation_id": conversation_id,
            "sql": sql,
            "validation": validation,
            "error": str(exc)
        }

    # ========================================================
    # 10. Handle execution failure
    # ========================================================

    if not execution.get(
        "success",
        False
    ):

        update_conversation(
            conversation_id,
            clarification=answer,
            status="execution_failed",
            generated_sql=sql
        )

        return {
            "status": "execution_failed",
            "conversation_id": conversation_id,
            "sql": sql,
            "validation": validation,
            "error": execution.get(
                "error",
                "Database execution failed."
            )
        }

    # ========================================================
    # 11. Generate final answer
    # ========================================================

    try:

        final_answer = await generate_answer(
            question=clarified_question,
            sql=sql,
            rows=execution.get(
                "rows",
                []
            )
        )

    except Exception as exc:

        update_conversation(
            conversation_id,
            clarification=answer,
            status="answer_generation_failed",
            generated_sql=sql,
            rows=execution.get(
                "rows",
                []
            )
        )

        return {
            "status": "answer_generation_failed",
            "conversation_id": conversation_id,
            "sql": sql,
            "validation": validation,
            "row_count": execution.get(
                "row_count",
                0
            ),
            "rows": execution.get(
                "rows",
                []
            ),
            "error": str(exc)
        }

    # ========================================================
    # 12. Update conversation
    # ========================================================

    update_conversation(
        conversation_id,
        clarification=answer,
        status="completed",
        generated_sql=sql,
        rows=execution.get(
            "rows",
            []
        ),
        final_answer=final_answer
    )

    # ========================================================
    # 13. Return final result
    # ========================================================

    return {
        "status": "completed",
        "conversation_id": conversation_id,
        "original_question": original_question,
        "clarification": answer,
        "sql": sql,
        "validation": validation,
        "row_count": execution.get(
            "row_count",
            0
        ),
        "rows": execution.get(
            "rows",
            []
        ),
        "answer": final_answer,
        "retrieved_schema": sql_result.get(
            "retrieved_schema",
            []
        )
    }